server_name: thiago-xps
user_name: thiagodefreitas
repositories:
  ipa_canopen:
    ros_distro: [groovy]
    robots: null
    jobs: [regular_build, downstream_build, nongraphics_test]
    poll: true
    dependencies: {}
    prio_ubuntu_distro: precise
    regular_matrix:
      oneiric: [amd64, i386]
      quantal: [amd64, i386]
      precise: [i386]
    prio_arch: amd64
    type: git
    url: git@github.com:thiagodefreitas/ipa_canopen.git
    version: almost_merged
email: thiagodefreitas@gmail.com
committer_email_enabled: false
