server_name: thiago-XPS
user_name: admin
repositories:
  ipa_canopen:
    ros_distro: [groovy]
    robots: null
    jobs: []
    poll: true
    dependencies: {}
    prio_ubuntu_distro: precise
    regular_matrix: {}
    prio_arch: amd64
    type: git
    url: git@github.com:ipa320/ipa_canopen.git
    version: groovy_dev
email: tdf@ipa.fhg.de
committer_email_enabled: false
